spring.application.name=processManager

# 서버 포트 설정 (기본 포트 8080)
server.port=8080

# MySQL 설정
spring.datasource.url=jdbc:mysql://localhost:13306/processmanager?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=test
spring.datasource.password=1234

# SSH 터널링 설정
ssh.host=1.209.148.228
ssh.port=2290
ssh.username=test
ssh.password=1234
ssh.remote-db-host=172.16.10.65
ssh.remote-db-port=3306
ssh.local-port=13306

# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# 테이블 자동 생성
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# 파일 인코딩 설정
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# JWT 시크릿 키
jwt.secret=processManagerSecretKeyForJwtTokenGenerationSecurity12345!@#

# Access Token 만료시간 (30분 = 1800000 밀리초)
jwt.access-expiration=1800000


# ==========================================
# Google OAuth2 (구글 소셜 로그인) 설정
# ==========================================
spring.security.oauth2.client.registration.google.client-id=637902813118-bm3r5cahr49bpf5qcor4kq4q3hvf2r86.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email