spring.application.name=processManager

# ?? ?? ?? (??? ?? ?? 8080 ??)
server.port=8080

# H2 Database ?? (??? ?? ???? DB)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT ??? ?
jwt.secret=processManagerSecretKeyForJwtTokenGenerationSecurity12345!@#

# Access Token ???? (30? = 1800000 ???)
jwt.access-expiration=1800000

# Refresh Token ???? (7? = 604800000 ???)
jwt.refresh-expiration=604800000

# ==========================================
# ? Google OAuth2 (?? ???) ??
# ==========================================
spring.security.oauth2.client.registration.google.client-id=637902813118-bm3r5cahr49bpf5qcor4kq4q3hvf2r86.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email